### ISSUE TITLE
404 bottone sorgente

### ISSUE THREAD

**Issue by danielaiozzo** [italia/design-linee-guida-docs#12]
Ciao @francescozaia @pdavide vi segnalo che se provo ad accedere ai sorgenti delle linee guida tramite il pulsante apposito, atterro sulla pagina 404 di github.

**Comment by pdavide** [comment]
Grazie @danielaiozzo. Problema risolto.

@francescozaia il problema era dovuto al fatto che il tag `2019.1` era un tag di tipo [`annotated`](https://git-scm.com/book/en/v2/Git-Basics-Tagging#_creating_tags), quindi con un suo checksum `sha-1`. Questo crea qualche problema a Docs che linka le pagine della versione relativa a un URL che contiene il checksum del tag e non quello del commit corrispondente. Il modo migliore per evitare questo errore è quello di creare le release dalla UI di GitHub e non da linea di comando.

**Comment by francescozaia** [comment]
Grazie, io avevo lanciato una build per provare e poi me n'ero già dimenticato _#noMultitasking_.
